name: Build Windows App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Instalar Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Instalar pnpm
        run: npm install -g pnpm

      - name: Instalar dependencias
        run: pnpm install

      - name: Build app
        run: pnpm run dist:win
        env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Subir instalador
        uses: actions/upload-artifact@v4
        with:
          name: CotizacionesApp
          path: dist/*.exe
         